import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// Generated by `npm run gen-api-docs` from the real OpenAPI spec exported by
// the ospi-platform backend (openapi/ospi-platform.json). Do not hand-edit
// this import target — regenerate it instead.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const apiSidebar = require('./docs/api-reference/reference/sidebar').default;

const sidebars: SidebarsConfig = {
  apiReferenceSidebar: [
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'intro',
        'authentication',
        'organizations-and-roles',
        'producers-and-ospi-codes',
        'products-and-variants',
        'categories-and-attributes',
        'documents',
        'inventory',
        'connections-and-sharing',
        'search',
        'ordering',
        'digital-product-passport',
        'webhooks',
      ],
    },
    ...apiSidebar,
  ],
};

export default sidebars;
