import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "reference/ospi-platform-api",
    },
    {
      type: "category",
      label: "health",
      items: [
        {
          type: "doc",
          id: "reference/health-controller-check",
          label: "HealthController_check",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "auth",
      items: [
        {
          type: "doc",
          id: "reference/auth-controller-register",
          label: "AuthController_register",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-login",
          label: "AuthController_login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-refresh",
          label: "AuthController_refresh",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-logout",
          label: "AuthController_logout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-logout-all",
          label: "AuthController_logoutAll",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/auth-controller-list-sessions",
          label: "AuthController_listSessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/auth-controller-revoke-session",
          label: "AuthController_revokeSession",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/auth-controller-create-api-client",
          label: "AuthController_createApiClient",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "roles",
      items: [
        {
          type: "doc",
          id: "reference/roles-controller-list-permissions",
          label: "RolesController_listPermissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/roles-controller-create",
          label: "RolesController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/roles-controller-list",
          label: "RolesController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/roles-controller-list-for-user",
          label: "RolesController_listForUser",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/roles-controller-assign",
          label: "RolesController_assign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/roles-controller-revoke",
          label: "RolesController_revoke",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "organizations",
      items: [
        {
          type: "doc",
          id: "reference/organizations-controller-get-own",
          label: "OrganizationsController_getOwn",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-update",
          label: "OrganizationsController_update",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-list-legal-entities",
          label: "OrganizationsController_listLegalEntities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-add-legal-entity",
          label: "OrganizationsController_addLegalEntity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-list-users",
          label: "OrganizationsController_listUsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-invite-user",
          label: "OrganizationsController_inviteUser",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/organizations-controller-list-roles",
          label: "OrganizationsController_listRoles",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "identity",
      items: [
        {
          type: "doc",
          id: "reference/identity-controller-create-producer",
          label: "IdentityController_createProducer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-list-producers",
          label: "IdentityController_listProducers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/identity-controller-issue-producer-code",
          label: "IdentityController_issueProducerCode",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-issue-ospi-identity",
          label: "IdentityController_issueOspiIdentity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-validate",
          label: "IdentityController_validate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-lookup",
          label: "IdentityController_lookup",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/identity-controller-retire",
          label: "IdentityController_retire",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-suspend",
          label: "IdentityController_suspend",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/identity-controller-reactivate",
          label: "IdentityController_reactivate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "products",
      items: [
        {
          type: "doc",
          id: "reference/products-controller-create",
          label: "ProductsController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list",
          label: "ProductsController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-create-bulk",
          label: "ProductsController_createBulk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-find-one",
          label: "ProductsController_findOne",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-update",
          label: "ProductsController_update",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/products-controller-validate",
          label: "ProductsController_validate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-publish",
          label: "ProductsController_publish",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-unpublish",
          label: "ProductsController_unpublish",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-retire",
          label: "ProductsController_retire",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-recall",
          label: "ProductsController_recall",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-add-variant",
          label: "ProductsController_addVariant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-variants",
          label: "ProductsController_listVariants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-register-serialized-unit",
          label: "ProductsController_registerSerializedUnit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-serialized-units",
          label: "ProductsController_listSerializedUnits",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-register-serialized-units-bulk",
          label: "ProductsController_registerSerializedUnitsBulk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-set-translation",
          label: "ProductsController_setTranslation",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/products-controller-remove-translation",
          label: "ProductsController_removeTranslation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-translations",
          label: "ProductsController_listTranslations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-create-relationship",
          label: "ProductsController_createRelationship",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/products-controller-list-relationships",
          label: "ProductsController_listRelationships",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/products-controller-remove-relationship",
          label: "ProductsController_removeRelationship",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "categories",
      items: [
        {
          type: "doc",
          id: "reference/categories-controller-create",
          label: "CategoriesController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/categories-controller-list",
          label: "CategoriesController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/categories-controller-list-pending",
          label: "CategoriesController_listPending",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/categories-controller-approve",
          label: "CategoriesController_approve",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/categories-controller-reject",
          label: "CategoriesController_reject",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "classification",
      items: [
        {
          type: "doc",
          id: "reference/classification-controller-create-attribute-definition",
          label: "ClassificationController_createAttributeDefinition",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-list-attribute-definitions",
          label: "ClassificationController_listAttributeDefinitions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-set-product-attribute-value",
          label: "ClassificationController_setProductAttributeValue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-set-variant-attribute-value",
          label: "ClassificationController_setVariantAttributeValue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-verify-attribute-value",
          label: "ClassificationController_verifyAttributeValue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-create-scheme",
          label: "ClassificationController_createScheme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-list-schemes",
          label: "ClassificationController_listSchemes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-add-node",
          label: "ClassificationController_addNode",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-list-nodes",
          label: "ClassificationController_listNodes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/classification-controller-assign",
          label: "ClassificationController_assign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-set-category-attribute-schema",
          label: "ClassificationController_setCategoryAttributeSchema",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/classification-controller-remove-category-attribute-schema",
          label: "ClassificationController_removeCategoryAttributeSchema",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/classification-controller-get-effective-attribute-schema",
          label: "ClassificationController_getEffectiveAttributeSchema",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "documents",
      items: [
        {
          type: "doc",
          id: "reference/documents-controller-create",
          label: "DocumentsController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/documents-controller-list",
          label: "DocumentsController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/documents-controller-upload",
          label: "DocumentsController_upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/documents-controller-find-one",
          label: "DocumentsController_findOne",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/documents-controller-update-metadata",
          label: "DocumentsController_updateMetadata",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/documents-controller-get-download-url",
          label: "DocumentsController_getDownloadUrl",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "locations",
      items: [
        {
          type: "doc",
          id: "reference/locations-controller-create",
          label: "LocationsController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/locations-controller-list",
          label: "LocationsController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/locations-controller-list-inventory",
          label: "LocationsController_listInventory",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "inventory",
      items: [
        {
          type: "doc",
          id: "reference/inventory-controller-upsert",
          label: "InventoryController_upsert",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/inventory-controller-list",
          label: "InventoryController_list",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "connections",
      items: [
        {
          type: "doc",
          id: "reference/connections-controller-request",
          label: "ConnectionsController_request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/connections-controller-list",
          label: "ConnectionsController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/connections-controller-accept",
          label: "ConnectionsController_accept",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/connections-controller-reject",
          label: "ConnectionsController_reject",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/connections-controller-suspend",
          label: "ConnectionsController_suspend",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/connections-controller-terminate",
          label: "ConnectionsController_terminate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "sharing",
      items: [
        {
          type: "doc",
          id: "reference/sharing-controller-create",
          label: "SharingController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/sharing-controller-list",
          label: "SharingController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/sharing-controller-revoke",
          label: "SharingController_revoke",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "partner",
      items: [
        {
          type: "doc",
          id: "reference/partner-controller-list-products",
          label: "PartnerController_listProducts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/partner-controller-get-product",
          label: "PartnerController_getProduct",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/partner-controller-get-inventory",
          label: "PartnerController_getInventory",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/partner-controller-list-documents",
          label: "PartnerController_listDocuments",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "search",
      items: [
        {
          type: "doc",
          id: "reference/search-controller-search-products",
          label: "SearchController_searchProducts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/search-controller-related",
          label: "SearchController_related",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/search-controller-resolve",
          label: "SearchController_resolve",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "offers",
      items: [
        {
          type: "doc",
          id: "reference/offers-controller-create",
          label: "OffersController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/offers-controller-list-mine",
          label: "OffersController_listMine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/offers-controller-list-for-product",
          label: "OffersController_listForProduct",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/offers-controller-withdraw",
          label: "OffersController_withdraw",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/offers-controller-set-buyer-minimum",
          label: "OffersController_setBuyerMinimum",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/offers-controller-list-buyer-minimums",
          label: "OffersController_listBuyerMinimums",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/offers-controller-remove-buyer-minimum",
          label: "OffersController_removeBuyerMinimum",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "orders",
      items: [
        {
          type: "doc",
          id: "reference/orders-controller-create-draft",
          label: "OrdersController_createDraft",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-list",
          label: "OrdersController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/orders-controller-get",
          label: "OrdersController_get",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/orders-controller-add-line",
          label: "OrdersController_addLine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-remove-line",
          label: "OrdersController_removeLine",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/orders-controller-submit",
          label: "OrdersController_submit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-accept",
          label: "OrdersController_accept",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-reject",
          label: "OrdersController_reject",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/orders-controller-update-status",
          label: "OrdersController_updateStatus",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "dpp",
      items: [
        {
          type: "doc",
          id: "reference/dpp-controller-create-profile",
          label: "DppController_createProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-list-profiles",
          label: "DppController_listProfiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-create-record",
          label: "DppController_createRecord",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-validate",
          label: "DppController_validate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-publish",
          label: "DppController_publish",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-suspend",
          label: "DppController_suspend",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-rotate-token",
          label: "DppController_rotateToken",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-get-owner",
          label: "DppController_getOwner",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/dpp-controller-get-public",
          label: "DppController_getPublic",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "webhooks",
      items: [
        {
          type: "doc",
          id: "reference/webhooks-controller-create",
          label: "WebhooksController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/webhooks-controller-list",
          label: "WebhooksController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/webhooks-controller-remove",
          label: "WebhooksController_remove",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/webhooks-controller-deliveries",
          label: "WebhooksController_deliveries",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/webhooks-controller-retry",
          label: "WebhooksController_retry",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "reference/schemas/registerdto",
          label: "RegisterDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/errordetaildto",
          label: "ErrorDetailDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/errorresponsedto",
          label: "ErrorResponseDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/logindto",
          label: "LoginDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/refreshdto",
          label: "RefreshDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createapiclientdto",
          label: "CreateApiClientDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createroledto",
          label: "CreateRoleDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/assignroledto",
          label: "AssignRoleDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updateorganizationdto",
          label: "UpdateOrganizationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createlegalentitydto",
          label: "CreateLegalEntityDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/inviteuserdto",
          label: "InviteUserDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createproducerdto",
          label: "CreateProducerDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/issueproducercodedto",
          label: "IssueProducerCodeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/issueospiidentitydto",
          label: "IssueOspiIdentityDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/validatecodedto",
          label: "ValidateCodeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createproductdto",
          label: "CreateProductDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/bulkcreateproductdto",
          label: "BulkCreateProductDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updateproductdto",
          label: "UpdateProductDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createvariantdto",
          label: "CreateVariantDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/registerserializedunitdto",
          label: "RegisterSerializedUnitDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/bulkregisterserializedunitdto",
          label: "BulkRegisterSerializedUnitDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setproducttranslationdto",
          label: "SetProductTranslationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createproductrelationshipdto",
          label: "CreateProductRelationshipDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createcategorydto",
          label: "CreateCategoryDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/rejectcategorydto",
          label: "RejectCategoryDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createattributedefinitiondto",
          label: "CreateAttributeDefinitionDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setattributevaluedto",
          label: "SetAttributeValueDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createclassificationschemedto",
          label: "CreateClassificationSchemeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createclassificationnodedto",
          label: "CreateClassificationNodeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/assignclassificationdto",
          label: "AssignClassificationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setcategoryattributeschemadto",
          label: "SetCategoryAttributeSchemaDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdocumentdto",
          label: "CreateDocumentDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/uploaddocumentdto",
          label: "UploadDocumentDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updatedocumentmetadatadto",
          label: "UpdateDocumentMetadataDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createlocationdto",
          label: "CreateLocationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/upsertinventorydto",
          label: "UpsertInventoryDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/requestconnectiondto",
          label: "RequestConnectionDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/sharingruledto",
          label: "SharingRuleDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createsharinggrantdto",
          label: "CreateSharingGrantDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createofferdto",
          label: "CreateOfferDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/setofferbuyerminimumdto",
          label: "SetOfferBuyerMinimumDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdraftorderdto",
          label: "CreateDraftOrderDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/addorderlinedto",
          label: "AddOrderLineDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/updateordergroupstatusdto",
          label: "UpdateOrderGroupStatusDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdppprofiledto",
          label: "CreateDppProfileDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createdpprecorddto",
          label: "CreateDppRecordDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "reference/schemas/createwebhooksubscriptiondto",
          label: "CreateWebhookSubscriptionDto",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
